### ISSUE TITLE
Browserifing issues

### ISSUE THREAD

**Issue by Malo87** [gja/react-templatify#3]
Hi, just changed a bit the case of the issue:

I'm trying to build the final js with the command:
browserify  -t [ react-templatify --extension .rt ] index.js --outfile runtime.js 

But when I try to use the the runtime.js in the page I got:

define is not defined

Any suggestion?

**Comment by gja** [comment]
Hi @Malo87. Would you mind sharing a bit of your code, or a minimum example that gets this problem?

**Comment by gja** [comment]
For some reason it is outputting in the AMD format, instead of the CommonJS format.

I'll try to fix this in the upcoming days. But, in the meanwhile, you should be able to execute with the following (do an `npm install --save deamdify` first)

`browserify -t react-templatify -t deamdify index.js --outfile runtime.js`

**Comment by gja** [comment]
@Malo87 just released it. Try upgrading to react-templatify 0.2.0

**Comment by Malo87** [comment]
Great! Yes, with 0.2.0 I can avoid to run the deamdify command in the chain!

Thanks
